# Generated by Django 2.1.4 on 2019-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmocafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пироженое',
                'verbose_name_plural': 'Пироженые',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Macaroon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Макарун',
                'verbose_name_plural': 'Макаруны',
            },
        ),
    ]
