# Generated by Django 2.2 on 2019-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmocafe', '0002_cupcake_drink_macaroon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Cupcake',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Macaroon',
        ),
    ]
