# Generated by Django 2.2 on 2019-05-30 21:09

import cosmocafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmocafe', '0003_auto_20190531_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=cosmocafe.models.upload_location),
        ),
    ]
