# Generated by Django 2.2 on 2019-05-30 21:32

import cosmocafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmocafe', '0004_auto_20190531_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Кекс',
                'verbose_name_plural': 'Кексы',
            },
        ),
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пироженое',
                'verbose_name_plural': 'Пироженые',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Macaroon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('text', models.TextField(verbose_name='Текст описания')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Макарун',
                'verbose_name_plural': 'Макаруны',
            },
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=cosmocafe.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_photo/'),
        ),
    ]
