# Generated by Django 2.2 on 2019-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmocafe', '0005_auto_20190531_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cupcake',
            options={},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='macaroon',
            options={},
        ),
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cake_photo/'),
        ),
        migrations.AddField(
            model_name='cupcake',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cupcake_photo/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Drink/'),
        ),
        migrations.AddField(
            model_name='macaroon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Macaroon_photo/'),
        ),
    ]
